version: '3'
services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../docker/db:/var/lib/mysql
      - ../docker/initdb.d:/docker-entrypoint-initdb.d
  backend:
    build: .
    container_name: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    image: node:16
    container_name: frontend
    ports:
      - '3001:3001'
    working_dir: /frontend
    command: sh -c "yarn install && yarn start"
    tty: true
    volumes:
      - ../frontend:/frontend